name: Hephaestus Configurator (Electron Build)

on:
  push:
    branches: [ main ]
    paths:
      - 'web-interface/**'
      - '!web-interface/README.md'

jobs:
  build-electron:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./web-interface
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web-interface/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build & Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: web-interface
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          args: "--config.publish.provider=github"
